# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNbIOdIgzl40MFMfjSKuT4EjvWdoJKd_
"""

import math

# ==========================================
# VARIABLES GLOBALES
# ==========================================
historial_operaciones = []
ultimo_resultado = None

# ==========================================
# FUNCIONES DE EVALUACIÓN AVANZADA
# ==========================================

def evaluar_expresion(expresion):
    """
    Evalúa expresiones matemáticas complejas de forma segura
    Soporta: operaciones básicas, funciones científicas y 'ans'
    """
    global ultimo_resultado

    # Reemplazar 'ans' con el último resultado
    if 'ans' in expresion and ultimo_resultado is not None:
        expresion = expresion.replace('ans', str(ultimo_resultado))

    # Diccionario de funciones permitidas (seguridad)
    funciones_permitidas = {
        'sqrt': math.sqrt,
        'log10': math.log10,
        'ln': math.log,
        'log': math.log,  # Alternativa para ln
        'sin': math.sin,
        'cos': math.cos,
        'tan': math.tan,
        'exp': math.exp,
        'abs': abs,
        'pow': pow,
        'round': round
    }

    try:
        resultado = eval(expresion, {"__builtins__": None}, funciones_permitidas)
        return resultado
    except ZeroDivisionError:
        return "Error: División por cero"
    except Exception as e:
        return f"Error: Expresión inválida - {str(e)}"


# ==========================================
# OPERACIONES BÁSICAS
# ==========================================

def sumar(a, b):
    """Suma dos números y devuelve el resultado"""
    return a + b

def restar(a, b):
    """Resta dos números y devuelve el resultado"""
    return a - b

def multiplicar(a, b):
    """Multiplica dos números y devuelve el resultado"""
    return a * b

def dividir(a, b):
    """Divide dos números con validación de división por cero"""
    if b == 0:
        return "Error: No se puede dividir por cero"
    return a / b

def potencia(a, b):
    """Calcula a elevado a la potencia b"""
    try:
        return pow(a, b)
    except Exception as e:
        return f"Error: {str(e)}"

def modulo(a, b):
    """Calcula el módulo (resto) de la división"""
    if b == 0:
        return "Error: No se puede calcular módulo con divisor cero"
    return a % b


# ==========================================
# OPERACIONES CIENTÍFICAS
# ==========================================

def raiz_cuadrada(a):
    """Calcula la raíz cuadrada de un número"""
    if a < 0:
        return "Error: No se puede calcular raíz cuadrada de número negativo"
    return math.sqrt(a)

def logaritmo_base10(a):
    """Calcula el logaritmo en base 10"""
    if a <= 0:
        return "Error: El logaritmo solo acepta números positivos"
    return math.log10(a)

def logaritmo_natural(a):
    """Calcula el logaritmo natural (base e)"""
    if a <= 0:
        return "Error: El logaritmo solo acepta números positivos"
    return math.log(a)


# ==========================================
# GESTIÓN DE HISTORIAL
# ==========================================

def agregar_a_historial(num1, num2, operacion, simbolo, resultado):
    """
    Agrega una operación al historial (máximo 5 operaciones)
    """
    if num2 is None:
        # Operaciones unarias (ej: √25 = 5)
        operacion_str = f"{simbolo}{num1} = {resultado}"
    else:
        # Operaciones binarias (ej: 5 + 3 = 8)
        operacion_str = f"{num1} {simbolo} {num2} = {resultado}"

    historial_operaciones.append(operacion_str)

    # Mantener solo las últimas 5 operaciones
    if len(historial_operaciones) > 5:
        historial_operaciones.pop(0)

def mostrar_historial():
    """Muestra el historial de operaciones realizadas"""
    print("\n" + "="*50)
    print("         HISTORIAL DE OPERACIONES")
    print("="*50)

    if not historial_operaciones:
        print("   No hay operaciones en el historial.")
    else:
        for idx, operacion in enumerate(historial_operaciones, 1):
            print(f"   {idx}. {operacion}")

    print("="*50)


# ==========================================
# INTERFAZ Y MENÚ
# ==========================================

def mostrar_menu():
    """Muestra el menú principal de la calculadora"""
    print("\n" + "="*50)
    print("      CALCULADORA CIENTÍFICA AVANZADA")
    print("="*50)
    print("  OPERACIONES BÁSICAS:")
    print("    1. Sumar              2. Restar")
    print("    3. Multiplicar        4. Dividir")
    print("    5. Potencia           6. Módulo")
    print("\n  OPERACIONES CIENTÍFICAS:")
    print("    7. Raíz cuadrada      8. Logaritmo base 10")
    print("    9. Logaritmo natural")
    print("\n  AVANZADO:")
    print("    10. Evaluar expresión (ej: 3+5*2, sqrt(16))")
    print("    11. Ver historial")
    print("    12. Salir")
    print("="*50)
    if ultimo_resultado is not None:
        print(f"  💾 Último resultado: {ultimo_resultado}")
        print(f"     (usa 'ans' en expresiones o responde 's' cuando se pregunte)")
        print("="*50)

def obtener_numero(mensaje, usa_ultimo_resultado=True):
    """
    Solicita un número al usuario con validación
    Permite usar el resultado anterior si está disponible
    """
    global ultimo_resultado

    while True:
        # Ofrecer usar el último resultado
        if usa_ultimo_resultado and ultimo_resultado is not None:
            usar_ultimo = input(f"¿Usar último resultado ({ultimo_resultado}) como {mensaje.lower()}? (s/n): ")
            if usar_ultimo.lower() == 's':
                return ultimo_resultado

        try:
            numero = float(input(mensaje))
            return numero
        except ValueError:
            print("❌ Error: Por favor ingresa un número válido")


# ==========================================
# FUNCIÓN PRINCIPAL
# ==========================================

def calculadora():
    """Función principal que ejecuta la calculadora"""
    global ultimo_resultado

    print("\n" + "🧮"*25)
    print("  ¡Bienvenido a la Calculadora Científica Avanzada!")
    print("🧮"*25)

    while True:
        mostrar_menu()
        opcion = input("\nElige una opción (1-12): ").strip()

        # Opción: Salir
        if opcion == "12":
            print("\n👋 ¡Gracias por usar la calculadora! Hasta luego.")
            break

        # Opción: Mostrar historial
        if opcion == "11":
            mostrar_historial()
            input("\nPresiona Enter para continuar...")
            continue

        # Opción: Evaluar expresión
        if opcion == "10":
            expresion = input("\nIngresa la expresión (ej: 3+5*2, sqrt(16), ans*2): ")
            resultado = evaluar_expresion(expresion)

            if isinstance(resultado, str) and resultado.startswith("Error"):
                print(f"\n❌ {resultado}")
            else:
                print(f"\n✅ Resultado:")
                print(f"   {expresion} = {resultado}")
                agregar_a_historial(expresion, None, "evaluación", "", resultado)
                ultimo_resultado = resultado

            input("\nPresiona Enter para continuar...")
            continue

        # Validar opción
        if opcion not in ["1", "2", "3", "4", "5", "6", "7", "8", "9"]:
            print("❌ Opción no válida. Por favor elige 1-12.")
            input("\nPresiona Enter para continuar...")
            continue

        # Operaciones unarias (un solo número)
        if opcion in ["7", "8", "9"]:
            num1 = obtener_numero("\nIngresa el número: ", usa_ultimo_resultado=True)

            if opcion == "7":
                resultado = raiz_cuadrada(num1)
                operacion = "raíz cuadrada"
                simbolo = "√"
            elif opcion == "8":
                resultado = logaritmo_base10(num1)
                operacion = "logaritmo base 10"
                simbolo = "log₁₀"
            elif opcion == "9":
                resultado = logaritmo_natural(num1)
                operacion = "logaritmo natural"
                simbolo = "ln"

            if isinstance(resultado, str) and resultado.startswith("Error"):
                print(f"\n❌ {resultado}")
            else:
                print(f"\n✅ Resultado de {operacion}:")
                print(f"   {simbolo}({num1}) = {resultado}")
                agregar_a_historial(num1, None, operacion, simbolo, resultado)
                ultimo_resultado = resultado

        # Operaciones binarias (dos números)
        else:
            num1 = obtener_numero("\nIngresa el primer número: ", usa_ultimo_resultado=True)
            num2 = obtener_numero("Ingresa el segundo número: ", usa_ultimo_resultado=False)

            # Mapeo de opciones a operaciones
            operaciones = {
                "1": (sumar, "suma", "+"),
                "2": (restar, "resta", "-"),
                "3": (multiplicar, "multiplicación", "×"),
                "4": (dividir, "división", "÷"),
                "5": (potencia, "potencia", "^"),
                "6": (modulo, "módulo", "%")
            }

            funcion, operacion, simbolo = operaciones[opcion]
            resultado = funcion(num1, num2)

            if isinstance(resultado, str) and resultado.startswith("Error"):
                print(f"\n❌ {resultado}")
            else:
                print(f"\n✅ Resultado de {operacion}:")
                print(f"   {num1} {simbolo} {num2} = {resultado}")
                agregar_a_historial(num1, num2, operacion, simbolo, resultado)
                ultimo_resultado = resultado

        input("\nPresiona Enter para continuar...")


# ==========================================
# EJECUCIÓN DEL PROGRAMA
# ==========================================

if __name__ == "__main__":
    calculadora()


# ==========================================
# MEJORAS IMPLEMENTADAS
# ==========================================
"""
✨ MEJORAS RESPECTO A LA VERSIÓN ORIGINAL:

1. Código más limpio y organizado con secciones claras
2. Mejor manejo de errores específicos (ZeroDivisionError)
3. Interfaz mejorada con emojis y formato más claro
4. Función 'input()' después de cada operación para mejor UX
5. Diccionario para mapear operaciones (reduce código repetitivo)
6. Validación mejorada en módulo y potencia
7. Comentarios más descriptivos
8. Mensajes de error más específicos
9. Nombres de funciones en singular (potencia vs potencias)
10. Uso de .strip() en la captura de opciones

🎓 CONCEPTOS NUEVOS DEMOSTRADOS:
- Diccionarios para simplificar código repetitivo
- Manejo específico de excepciones
- Mejores prácticas de UX en terminal
- Organización de código en secciones
"""



import math

historial_operaciones = []
ultimo_resultado = None #variable p/guadar operation anterior

def evaluar_expresion(expresion):
   global ultimo_resultado

   if 'ans' in expresion and ultimo_resultado is not None:
     expresion = expresion.replace('ans', str(ultimo_resultado))
   # ans es el resultado de la operacion anterior
   #Diccionario de funciones permitidas
   funciones_permitidas = {
      'sqrt':math.sqrt,
      'log10':math.log10,
      'ln':math.log,
      'sin':math.sin,
      'cos':math.cos,
      'tan':math.tan,
      'exp':math.exp
   }
   try:
      resultado = eval(expresion, {"__builtins__":None}, funciones_permitidas)
      return resultado
   except Exception as e:
      return f"Error: {str(e)}"


def sumar(a, b):
   """Suma dos numero y devuelve el resultado"""
   return a + b

def restar(a, b):
  return a - b

def multiplicar(a, b):
  return a * b

def dividir(a, b):
  if b != 0:
    return a / b
  else:
    return "Error: No se puede dividir por cero"

def potencias(a, b):
  return pow(a, b)

def modulo(a, b):
  return a % b

def raiz_cuadrada(a):
  if a >= 0:
    return math.sqrt(a)
  else:
    return "Error no se puede calcular rai cuadrada de un numero negativo"

def logaritmo_base10(a):
  if a > 0:
    return math.log10(a)
  else:
    return "Error: No se puede calcular el logaritmo de un numero negativo"

def logaritmo_natural(a):
  if a > 0:
    return math.log(a)
  else:
    return "Error: No se puede calcular el logaritmo de un numero negativo"

def agregar_a_historial(num1, num2, operation, simbolo, resultado):
   if num2 is None:
      operation_str = f"{simbolo}{num1}={resultado}"
   else:
      operation_str = f"{num1} {simbolo} {num2} = {resultado}"
   #Crea un string que representa la operación completa ej: 5 + 4 = 9
   historial_operaciones.append(operation_str)
   if len(historial_operaciones) > 5:
      historial_operaciones.pop(0)  # Elimina la operación más antigua

def mostrar_historial():
    """Muestra el historial de operaciones"""
    print("\n--- HISTORIAL DE OPERACIONES ---")
    if not historial_operaciones:
        print("No hay operaciones en el historial.")
    else:
        for idx, operacion in enumerate(historial_operaciones, 1):
            print(f"{idx}. {operacion}")
    print("----------------------------------")

def mostrar_menu():
    """Muestra las funciones disponibles al usuario"""
    print("\n" + "="*50)
    print("      CALCULADORA SIMPLE Y CIENTIFICA")
    print("="*50)
    print("1. Sumar")
    print("2. Restar")
    print("3. Multiplicar")
    print("4. Dividir")
    print("5. Potencia")
    print("6. Modulo")
    print("7. Raiz cuadrada")
    print("8. Logaritmo base 10")
    print("9. Logaritmo natural")
    print("10. Evaluar Expresion Matematica")
    print("11. Mostrar Historial ")
    print("12. Salir")
    print("="*50)

def obtener_numero(mensaje, usa_ultimo_resultado=True):
   global ultimo_resultado
   while True:
      if usa_ultimo_resultado and ultimo_resultado is not None:
         usar_ultimo = input(f"\n¿Quieres usar el último resultado ({ultimo_resultado}) como {mensaje.lower()}? (s/n): ")
         if usar_ultimo.lower() == 's':
            return ultimo_resultado
      try:
         numero = float(input(mensaje))
         return numero
      except ValueError:
         print("❌ Error: Por favor ingresa un número válido")

def calculadora():
  global ultimo_resultado
  while True:
    mostrar_menu()
    opcion = input("Elige una opción (1-12): ")

    if opcion == "12":
      print("\n Gracias por usar la calculadora. ¡Hasta luego!")
      break

    if opcion == "11":
      mostrar_historial()
      continue

    if opcion == "10":
       expresion = input("Ingresa la expresion matematicav(ej: 3 + 5 * 2): ")
       resultado = evaluar_expresion(expresion)
       if isinstance(resultado, str) and resultado.startswith("Error"):
           print(f"\n {resultado}")
       else:
          print(f"\n ✅ Resultado de la expresion:")
          print(f"   {expresion} = {resultado}")
          agregar_a_historial(expresion, None, "evaluation", "", resultado)
          ultimo_resultado = resultado
          continue

    if opcion not in ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]:
      print("❌ Opción no válida. Por favor elige una opción válida.")
      continue

    if opcion in ["7", "8", "9"]:
       num1 = obtener_numero("Ingresa el primer número: ",usa_ultimo_resultado=True)
       if opcion == "7":
          resultado = raiz_cuadrada(num1)
          operation = "raiz cuadrada"
          simbolo = "√"
       elif opcion == "8":
          resultado = logaritmo_base10(num1)
          operation = "logaritmo base 10"
          simbolo = "log10("
       elif opcion == "9":
          resultado = logaritmo_natural(num1)
          operation = "logaritmo natural"
          simbolo = "ln("
       if isinstance(resultado, str) and resultado.startswith("Error"):
           print(f"\n {resultado}")
       else:
          print(f"\n ✅ Resultado de la operación:")
          print(f"   {simbolo} {num1} = {resultado}")
          agregar_a_historial(num1, None, operation, simbolo, resultado)
          ultimo_resultado = resultado

    else:
       num1 = obtener_numero("Ingresar el primer numero: ", usa_ultimo_resultado=True)
       num2 = obtener_numero("Ingresar el segundo numero: ", usa_ultimo_resultado=False) # Added space

       if opcion == "1":
         resultado = sumar(num1, num2)
         operation = "suma"
         simbolo = "+"

       elif opcion == "2":
         resultado = restar(num1, num2)
         operation = "resta"
         simbolo = "-"

       elif opcion == "3":
          resultado = multiplicar(num1, num2)
          operation = "multiplicacion"
          simbolo = "*"

       elif opcion == "4":
          if num2 != 0:
            resultado = dividir(num1, num2)
            operation = "division"
            simbolo = "/"
          else:
            resultado = dividir(num1, num2) # Call dividir to get the error message
            operation = "division"
            simbolo = "/"

       elif opcion == "5":
          resultado = potencias(num1, num2)
          operation = "potencia"
          simbolo = "^"

       elif opcion == "6":
          resultado = modulo(num1, num2)
          operation = "modulo"
          simbolo = "%"

       elif opcion == "7":
          resultado = raiz_cuadrada(num1)
          operation = "raiz cuadrada"
          simbolo = "√"

       elif opcion == "8":
          resultado = logaritmo_base10(num1)
          operation = "logaritmo base 10"
          simbolo = "log10("

       elif opcion == "9":
          resultado = logaritmo_natural(num1)
          operation = "logaritmo natural"
          simbolo = "ln("

       if isinstance(resultado, str) and resultado.startswith("Error"):
           print(f"\n {resultado}")
       else:
          print(f"\n ✅ Resultado de la operación:")
          print(f"   {num1} {simbolo} {num2} = {resultado}")
          agregar_a_historial(num1, num2, operation, simbolo, resultado)
          ultimo_resultado = resultado


    continuar = input("\n¿Deseas realizar otra operación? (s/n): ")
    if continuar.lower() != 's':
      print("\n👋 ¡Gracias por usar la calculadora! Hasta pronto.")
      break

if __name__ == "__main__":
  calculadora()